"""Test samples generated by local LLMs via Ollama.

These samples test whether Binoculars detects AI text from different
model architectures (Qwen3, Gemma3, Llama3.1) better than from Claude.
All generated 2026-04-02 on Mac Studio via Ollama.
"""

OLLAMA_SAMPLES = [
    # --- Qwen3:8B ---
    {
        "id": "ollama_qwen3_specific_aims",
        "label": "ai_generated",
        "source": "qwen3:8b",
        "section": "Specific Aims",
        "text": (
            "Aim 1: To elucidate the dynamic interplay between neuroinflammation "
            "and amyloid-beta pathology in Alzheimer's disease progression using "
            "in vivo imaging and transcriptomic profiling. "
            "Aim 2: To identify key molecular pathways and cell-type-specific "
            "mechanisms mediating neuroinflammatory responses in human brain "
            "tissues from Alzheimer's patients. "
            "Aim 3: To evaluate the therapeutic potential of targeting microglial "
            "activation and complement signaling in preclinical models of "
            "Alzheimer's disease, with emphasis on translational relevance for "
            "early intervention. "
            "Aim 4: To develop and validate non-invasive biomarkers of "
            "neuroinflammation for early detection and monitoring of Alzheimer's "
            "disease progression. "
            "Aim 5: To establish a framework for integrating multi-omics data "
            "to prioritize drug targets and predict patient responses to "
            "anti-inflammatory therapies."
        ),
    },
    {
        "id": "ollama_qwen3_significance",
        "label": "ai_generated",
        "source": "qwen3:8b",
        "section": "Significance",
        "text": (
            "Cardiovascular disease remains a leading cause of mortality worldwide, "
            "with myocardial infarction and heart failure imposing substantial "
            "morbidity and economic burden. Despite advances in medical and "
            "interventional therapies, the heart's limited regenerative capacity "
            "following injury persists as a critical barrier to long-term recovery, "
            "necessitating novel therapeutic strategies. Current interventions "
            "primarily focus on symptom management rather than restoring cardiac "
            "function, underscoring an urgent need for approaches that harness "
            "endogenous regenerative mechanisms. This research seeks to address "
            "this gap by investigating the molecular and cellular pathways "
            "governing cardiac regeneration, with the goal of developing targeted "
            "therapies to enhance myocardial repair. Successful outcomes could "
            "revolutionize treatment paradigms for patients with ischemic or "
            "degenerative heart disease, offering durable functional recovery and "
            "reducing reliance on mechanical support. By elucidating the mechanisms "
            "underlying cardiac regeneration, this work holds translational "
            "potential to advance precision medicine and improve clinical outcomes, "
            "ultimately mitigating the global burden of cardiovascular disease."
        ),
    },

    # --- Gemma3:12B ---
    {
        "id": "ollama_gemma3_specific_aims",
        "label": "ai_generated",
        "source": "gemma3:12b",
        "section": "Specific Aims",
        "text": (
            "The overarching goal of this project is to elucidate the role of "
            "microglia-derived exosomes in propagating neuroinflammation and "
            "accelerating amyloid-beta plaque deposition in Alzheimer's disease "
            "(AD). We hypothesize that AD-affected microglia release exosomes "
            "enriched with pro-inflammatory cytokines and microRNAs, which are "
            "subsequently internalized by neighboring neurons and astrocytes, "
            "fostering a deleterious inflammatory cascade. Aim 1 will characterize "
            "the protein and microRNA cargo of exosomes released from primary "
            "microglia cultured under AD-relevant stimulation. Aim 2 will "
            "determine if exosome uptake by recipient neurons and astrocytes "
            "increases amyloid-beta production and deposition in vitro. Aim 3 "
            "will assess the impact of exosome blockade on neuroinflammation and "
            "plaque burden in a 5xFAD mouse model of AD. Successful completion "
            "of these aims will provide critical mechanistic insights into "
            "microglial exosome-mediated neuroinflammation and identify novel "
            "therapeutic targets for AD intervention."
        ),
    },
    {
        "id": "ollama_gemma3_significance",
        "label": "ai_generated",
        "source": "gemma3:12b",
        "section": "Significance",
        "text": (
            "Cardiovascular disease (CVD) remains the leading cause of mortality "
            "globally, and despite advances in therapeutic interventions, "
            "significant morbidity and mortality persist due to the limited "
            "regenerative capacity of the adult mammalian heart. Myocardial "
            "infarction (MI) results in irreversible cardiomyocyte loss and scar "
            "formation, leading to contractile dysfunction and heart failure. "
            "Current therapies primarily focus on symptom management and fail to "
            "restore cardiac architecture or function. This proposal addresses a "
            "critical unmet need: developing strategies to stimulate endogenous "
            "cardiac regeneration following MI. Our preliminary data suggest a "
            "novel regulatory mechanism which, when manipulated, demonstrates "
            "promising early indicators of cardiomyocyte proliferation and "
            "angiogenesis in a murine model. Successful completion of this "
            "research will significantly advance our understanding of cardiac "
            "regeneration pathways, providing a foundation for the development "
            "of targeted therapeutic interventions to promote myocardial repair "
            "and improve outcomes for patients suffering from CVD. The potential "
            "translation of these findings represents a paradigm shift from "
            "palliative care to active cardiac restoration."
        ),
    },

    # --- Llama3.1:8B ---
    {
        "id": "ollama_llama31_specific_aims",
        "label": "ai_generated",
        "source": "llama3.1:8b",
        "section": "Specific Aims",
        "text": (
            "The specific aims of this proposal are to investigate the role of "
            "neuroinflammation in the pathogenesis of Alzheimer's disease (AD) "
            "and to elucidate the underlying mechanisms by which inflammation "
            "contributes to disease progression. "
            "Aim 1: To identify the key inflammatory cell types and mediators "
            "involved in AD pathology using a combination of immunohistochemical "
            "and flow cytometric analysis of post-mortem brain tissue from AD "
            "patients and non-demented controls. "
            "Aim 2: To determine the functional consequences of neuroinflammation "
            "on AD-related molecular pathways, including amyloid-beta production "
            "and clearance, tau phosphorylation, and neuronal integrity, using "
            "in vitro and in vivo models of neuroinflammation. "
            "Aim 3: To explore the therapeutic potential of targeting inflammatory "
            "pathways in AD using small molecule inhibitors and antibody therapies "
            "that selectively modulate inflammatory responses, and to assess "
            "their effects on disease-relevant biomarkers and cognition in a "
            "mouse model of AD."
        ),
    },
    {
        "id": "ollama_llama31_approach",
        "label": "ai_generated",
        "source": "llama3.1:8b",
        "section": "Approach",
        "text": (
            "Our proposed approach to addressing sickle cell disease through "
            "CRISPR gene editing is multifaceted and grounded in the latest "
            "advances in genome editing technologies and their application in "
            "human disease. We will utilize the precision of CRISPR-Cas9 to "
            "target and disrupt the HBB gene, which encodes the beta-globin "
            "subunit of hemoglobin, thereby preventing the production of the "
            "abnormal hemoglobin that characterizes sickle cell disease. Our "
            "strategy involves the use of in vitro and in vivo models to "
            "optimize the CRISPR system and ensure its safety and efficacy. We "
            "will employ gene editing in human hematopoietic stem cells (HSCs) "
            "to achieve a stable and long-term correction of the HBB gene. "
            "Furthermore, we will utilize cutting-edge genome analysis and "
            "modeling tools to predict and mitigate potential off-target effects "
            "and optimize the CRISPR system for maximal therapeutic impact. Our "
            "research will provide critical insights into the feasibility and "
            "efficacy of CRISPR-mediated gene editing for sickle cell disease."
        ),
    },
]


ALL_OLLAMA_SAMPLES = OLLAMA_SAMPLES


if __name__ == "__main__":
    print(f"Ollama-generated test samples: {len(ALL_OLLAMA_SAMPLES)}")
    for s in ALL_OLLAMA_SAMPLES:
        words = len(s["text"].split())
        print(f"  [{s['source']:>12}] {s['id']:<40} ({words} words)")
