"""Test samples generated by local LLMs via Ollama.

Backward-compatible shim — samples are now stored as individual YAML files
in tests/samples/<section>/. This module re-exports from the YAML loader.
"""

from tests.sample_loader import (
    OLLAMA_SAMPLES,
    ALL_OLLAMA_SAMPLES,
)

__all__ = [
    "OLLAMA_SAMPLES",
    "ALL_OLLAMA_SAMPLES",
]


if __name__ == "__main__":
    print(f"Ollama-generated test samples: {len(ALL_OLLAMA_SAMPLES)}")
    for s in ALL_OLLAMA_SAMPLES:
        words = len(s["text"].split())
        source = s.get("source", "unknown")
        print(f"  [{source:>12}] {s['id']:<40} ({words} words)")
